from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path

from .model import CentroidModel, save_model, train_centroid_model


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train the heuristic selector model from benchmark features."
    )
    parser.add_argument(
        "--dataset",
        default="benchmarks/training_dataset.csv",
        help="CSV generated by benchmarks pipeline containing feature columns and a winner label.",
    )
    parser.add_argument(
        "--output",
        default="models/method_selector.pkl",
        help="Path where the trained model (pickle) will be stored.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    dataset_path = Path(args.dataset)
    if not dataset_path.exists():
        raise FileNotFoundError(
            f"Training dataset not found at {dataset_path}. "
            "Run the benchmark pipeline first."
        )

    rows = _load_dataset(dataset_path)
    features = [row[0] for row in rows]
    labels = [row[1] for row in rows]
    label_counts = Counter(labels)

    model: CentroidModel = train_centroid_model(rows)
    save_model(model, args.output)

    print(f"Model saved to {args.output}")
    print("Label distribution:")
    for label, count in label_counts.most_common():
        print(f"  {label}: {count}")


def _load_dataset(path: Path):
    with path.open("r", newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        rows = []
        for row in reader:
            instance_name = row.pop("instance_name", None)
            winner = row.pop("winner", None)
            if winner is None:
                raise ValueError("Dataset is missing 'winner' column.")
            feature_vector = {key: float(value) for key, value in row.items()}
            rows.append((feature_vector, winner))
    if not rows:
        raise ValueError("Training dataset is empty.")
    return rows


if __name__ == "__main__":
    main()
